### ISSUE TITLE
Mobile full artilce view does not wrap text

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#1006]
![selection_073](https://cloud.githubusercontent.com/assets/1326120/9926096/6c912e28-5ce0-11e5-9e28-f4be96c83a8b.png)

**Comment by luchia** [comment]
This is actually to do with the bug you found where the article text is underneath the gray bar. It's caused by long strings not wrapping. I have fixed this in my PR today.

**Comment by luchia** [comment]
PR submitted. This has been fixed. It caused another bug (#1008) which has also been fixed.

**Comment by romichg** [comment]
This still doesn't work with the latest stuff.

![selection_003](https://cloud.githubusercontent.com/assets/1326120/10079764/ec39d592-62b9-11e5-9df8-16ee06162b18.png)

**Comment by luchia** [comment]
Very strange, working in all of my browsers. What is the browser you're using?

![screen shot 2015-09-25 at 8 15 58 am](https://cloud.githubusercontent.com/assets/4547737/10088395/e8a6fe6a-635d-11e5-8d31-6012d4932152.png)
![screen shot 2015-09-25 at 8 16 25 am](https://cloud.githubusercontent.com/assets/4547737/10088396/e8ac01c6-635d-11e5-9304-64cf4c6cdcd9.png)
![screen shot 2015-09-25 at 8 16 41 am](https://cloud.githubusercontent.com/assets/4547737/10088397/e8cf160c-635d-11e5-827f-45615c31a6fe.png)

**Comment by romichg** [comment]
Its not working on your FF, look closer in your screenshot :)

**Comment by luchia** [comment]
I did change one small thing so let me know if that fixes the issue for you.

**Comment by romichg** [comment]
um no :)

**Comment by luchia** [comment]
![screen shot 2015-09-26 at 7 05 42 pm](https://cloud.githubusercontent.com/assets/4547737/10116749/e3002930-6481-11e5-8acd-2796e9a59ab8.png)

Same as #1008, I had to force it and didn't realise.

**Comment by romichg** [comment]
fixed as well.. great!
