### ISSUE TITLE
Small alignment issue with Search button

### ISSUE THREAD

**Issue by DinisCruz** [TeamMentor/TM_4_0_Design#218]
![image](https://cloud.githubusercontent.com/assets/656739/5662116/7ec00d1e-972c-11e4-8c22-080b7addb107.png)

**Comment by DinisCruz** [comment]
I think the prob is related to **vertical-align: middle;'** style

If it is, here is a test that checks for it

```coffee
  it.only 'Issue 218 - Small alignment issue with Search button', (done)->
    jade.login_As_User ->
      jade.page_User_Main (html, $)->
        juice   = require('juice')
        cheerio = require('cheerio')
        baseUrl = page.tm_Server.log();
        juice.juiceContent html, { url: baseUrl}, (err, cssHtml)->
          $css = cheerio.load(cssHtml)
          attributes = $css('.input-group-btn').attr()
          attributes.assert_Is({ class: 'input-group-btn', style: 'display: table-cell; border-left: none; width: 100px; max-width: 100%; vertical-align: middle;' })
          attributes.style.assert_Contains('vertical-align: middle;')                          
          done()
```

**Comment by roman87** [comment]
making this a P0 for @luchia  since its the only P0 on your plate.

**Comment by luchia** [comment]
This has been fixed but I can't push my changes until I sort out my issues with graph DB.

![screen shot 2015-01-12 at 8 49 36 am](https://cloud.githubusercontent.com/assets/4547737/5697292/00bfacda-9a38-11e4-9e4d-a11e541e4e2e.png)

**Comment by roman87** [comment]
Whats the issue # for you GraphDB problem :)

**Comment by luchia** [comment]
Woops, forgot to create one - it was a silly thing where I couldn't create a token because I don't have a local version of tm-dev.

This has been fixed.

**Comment by roman87** [comment]
I'll take the QA on that one.

**Comment by DinisCruz** [comment]
still not 100%
![image](https://cloud.githubusercontent.com/assets/656739/5726117/bf9f4250-9b50-11e4-83c5-3a96d3d8bc57.png)

http://tm-dev-01.teammentor.net:1337/

**Comment by luchia** [comment]
![screen shot 2015-01-14 at 9 25 13 am](https://cloud.githubusercontent.com/assets/4547737/5731461/5f9ba61c-9bcf-11e4-8954-5fc27fd5fa1a.png)

![screen shot 2015-01-14 at 9 25 20 am](https://cloud.githubusercontent.com/assets/4547737/5731462/5fa0fc02-9bcf-11e4-86c0-bfa55eddf0e2.png)

**Comment by luchia** [comment]
This has been fixed on the Dev branch, @roman87.

**Comment by roman87** [comment]
Looks good. Closing
