### ISSUE TITLE
Images are tiled on a 27" display at 2560x1440 resolution

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#356]
This is one of those amazing issues you can only get through field trials. This one comes from  Brandon Cooper.  

As additional info,  
"I tested it on Chrome, Safari and Firefox and they all have the same tiling behavior. I’m currently working on a MacOS 10.10 machine with a 27” 2560x1440 display, I also tested it on Ubuntu 14.04 with the same results." - Ubuntu is the VM running on Mac.

The new version of TM is looking great! Design and functionality have improved by a massive scale since I joined the SI team. I really like the main landing page, design wise its appealing to the eye and radiates professionalism. The green/grey color scheme contrasts nicely with the Team Professor pallet as well.

![selection_075](https://cloud.githubusercontent.com/assets/1326120/5950820/0766ecfe-a72d-11e4-8af7-57eaf8b12853.png)

One this I noticed, on my high resolution display (2560x1440), the banner images on the top and bottom of the page are tiled horizontally. The images themselves are a great pick, but when they are tiled it takes away from the page a bit. In my option, having a light grey or muted gradient on either side would improve the ascetics when displayed on a large screen. Other than that, the scaling seems to work great on everything from my desktop to iPhone.

**Comment by roman87** [comment]
And this comes from my own testing. Reducing the HiDPI scaling on my 14" screen
![selection_076](https://cloud.githubusercontent.com/assets/1326120/5950875/bda9388c-a72d-11e4-8c52-7e76176303eb.png)

**Comment by luchia** [comment]
I think I fixed this Roman (I can't recreate it on my machine) so can you please check this one for me?

**Comment by roman87** [comment]
They are no longer tiled, but left justified. Looks a bit weird. In firefox you ca probably try to set in about:config  layout.css.devPixelsPerPx to anything less then one (like 0.5) and you will probably be able to duplicate this.

![selection_087](https://cloud.githubusercontent.com/assets/1326120/6098422/040e4c96-afac-11e4-9ed1-ff2253e494f6.png)
![selection_086](https://cloud.githubusercontent.com/assets/1326120/6098423/07659890-afac-11e4-97e0-206f500f0835.png)

**Comment by luchia** [comment]
This relates to the sizing of the background images and has been fixed in the referenced commit.

![screen shot 2015-02-10 at 11 39 55 am](https://cloud.githubusercontent.com/assets/4547737/6119808/a9fd5444-b119-11e4-8537-457d8298183c.png)
![screen shot 2015-02-10 at 11 39 56 am](https://cloud.githubusercontent.com/assets/4547737/6119809/aa0506ee-b119-11e4-8348-81a7f814cebb.png)
![screen shot 2015-02-10 at 11 39 58 am](https://cloud.githubusercontent.com/assets/4547737/6119810/aa0ee614-b119-11e4-8eed-dbedd8a794a0.png)

**Comment by luchia** [comment]
Taking this back because now we have resizing issues for this fix -

![screen shot 2015-02-11 at 12 06 06 pm](https://cloud.githubusercontent.com/assets/4547737/6140637/70dec13e-b1e6-11e4-97b0-b43563d05dd2.png)
![screen shot 2015-02-11 at 12 06 09 pm](https://cloud.githubusercontent.com/assets/4547737/6140638/70e6593a-b1e6-11e4-80cb-23c83bcec489.png)
![screen shot 2015-02-11 at 12 06 12 pm](https://cloud.githubusercontent.com/assets/4547737/6140639/70ed3598-b1e6-11e4-9a17-315821889034.png)

**Comment by luchia** [comment]
This has been fixed in the referenced commit.

**Comment by roman87** [comment]
Still the same issue:
![selection_096](https://cloud.githubusercontent.com/assets/1326120/6157045/8ac15866-b20c-11e4-8c32-8e986e38b2a5.png)

**Comment by luchia** [comment]
Alright, I'm pretty sure I fixed it this time -

![screen shot 2015-02-12 at 5 19 46 pm](https://cloud.githubusercontent.com/assets/4547737/6163441/497f4d0e-b2de-11e4-8456-0fb2cc7f6e84.png)
![screen shot 2015-02-12 at 5 19 50 pm](https://cloud.githubusercontent.com/assets/4547737/6163442/49a5d1b8-b2de-11e4-888c-dc6e7f079124.png)
![screen shot 2015-02-12 at 5 19 52 pm](https://cloud.githubusercontent.com/assets/4547737/6163443/49aaca92-b2de-11e4-8ef3-cce46726b289.png)
![screen shot 2015-02-12 at 5 19 55 pm](https://cloud.githubusercontent.com/assets/4547737/6163444/49cb8ea8-b2de-11e4-8e5c-e050332df863.png)
![screen shot 2015-02-12 at 5 20 03 pm](https://cloud.githubusercontent.com/assets/4547737/6163445/49cd3046-b2de-11e4-8f1b-3b95c93ec801.png)
![screen shot 2015-02-12 at 5 20 06 pm](https://cloud.githubusercontent.com/assets/4547737/6163446/49cdc9f2-b2de-11e4-8a13-31443104ee49.png)
![screen shot 2015-02-12 at 5 20 10 pm](https://cloud.githubusercontent.com/assets/4547737/6163447/49cec1a4-b2de-11e4-9368-3b51876d9a3d.png)
![screen shot 2015-02-12 at 5 33 54 pm](https://cloud.githubusercontent.com/assets/4547737/6163448/49d07ad0-b2de-11e4-98b6-ea1683fe9ab2.png)
![screen shot 2015-02-12 at 5 33 58 pm](https://cloud.githubusercontent.com/assets/4547737/6163449/49d68fce-b2de-11e4-8403-8c4159ac4cf6.png)
![screen shot 2015-02-12 at 5 34 00 pm](https://cloud.githubusercontent.com/assets/4547737/6163450/49f8ba04-b2de-11e4-8555-5188aca5cd1d.png)
![screen shot 2015-02-12 at 5 34 02 pm](https://cloud.githubusercontent.com/assets/4547737/6163452/49fa1f8e-b2de-11e4-80f4-12baca7e941c.png)
![screen shot 2015-02-12 at 5 34 06 pm](https://cloud.githubusercontent.com/assets/4547737/6163451/49f9776e-b2de-11e4-82ed-e0f6078c0517.png)
![screen shot 2015-02-12 at 5 34 08 pm](https://cloud.githubusercontent.com/assets/4547737/6163453/49fd3b4c-b2de-11e4-90b5-596de8aa6b5a.png)

**Comment by roman87** [comment]
Not really :) still a problem here:

![selection_105](https://cloud.githubusercontent.com/assets/1326120/6192988/32f0c3b8-b385-11e4-9173-639be45690fb.png)

**Comment by luchia** [comment]
To fix this, I ended up having to amend the size of the background images. This is because we use a sprite and when I attached a background-size (cover, auto etc) it affects the positioning of the sprite on resize. Basically, we can't have responsive sprites without it being a massive pain in the neck. I am going to look at switching us over to SVGs for Flare so that we can have background images that resize and look nice on mobile for our users.

In the mean time, here's screens of my work -

![screen shot 2015-02-17 at 10 21 57 am](https://cloud.githubusercontent.com/assets/4547737/6221155/6cb85d74-b68f-11e4-9162-ed7cb9c90009.png)
![screen shot 2015-02-17 at 10 22 00 am](https://cloud.githubusercontent.com/assets/4547737/6221156/6cba16e6-b68f-11e4-80a8-453ebfb18615.png)
![screen shot 2015-02-17 at 10 22 03 am](https://cloud.githubusercontent.com/assets/4547737/6221157/6cbeb76e-b68f-11e4-969f-52c74c345af3.png)
![screen shot 2015-02-17 at 10 22 06 am](https://cloud.githubusercontent.com/assets/4547737/6221158/6cbfaaf2-b68f-11e4-9682-daa2cbd3b15e.png)
![screen shot 2015-02-17 at 10 22 08 am](https://cloud.githubusercontent.com/assets/4547737/6221159/6cc1cd64-b68f-11e4-8e67-d53091bcab5f.png)
![screen shot 2015-02-17 at 10 22 12 am](https://cloud.githubusercontent.com/assets/4547737/6221160/6cc3614c-b68f-11e4-957d-5c506e84cf59.png)
![screen shot 2015-02-17 at 10 22 37 am](https://cloud.githubusercontent.com/assets/4547737/6221161/6ce4e9de-b68f-11e4-8070-ccececd78988.png)
![screen shot 2015-02-17 at 10 22 40 am](https://cloud.githubusercontent.com/assets/4547737/6221162/6ce6cd26-b68f-11e4-91b5-4eb0a96a9933.png)
![screen shot 2015-02-17 at 10 22 44 am](https://cloud.githubusercontent.com/assets/4547737/6221163/6ced557e-b68f-11e4-9e54-2e2caf466785.png)

**Comment by roman87** [comment]
Yey, finally works! 
![selection_109](https://cloud.githubusercontent.com/assets/1326120/6223240/7c03055c-b632-11e4-85a1-e50460f13ccf.png)
Will follow up with Brandon.

**Comment by roman87** [comment]
Following up with Brandon.

**Comment by roman87** [comment]
Brandon says it is still an issue. I just checked with the latest image and we still have the problem. 
![selection_127](https://cloud.githubusercontent.com/assets/1326120/6359949/71ab3562-bc44-11e4-8a6d-a2afbdc1dfc3.png)

**Comment by luchia** [comment]
As per our meeting this morning, we decided to create another media query that addresses this issue and the issue of delivering high-quality images to users on retina and high ratio pixel displays. 

This solution also makes use of the media queries that Flare has which populate the divs with a specific image depending on the screen/device width. If the user is on mobile, it sends the smallest image and so on. It's unlikely that a user will be moving from small screen to wide screen as often as we are, so it will be effective in limiting how much of our users resourced we will need to load our landing pages. You can see the result of this below:

Index -
![screen shot 2015-02-26 at 2 21 03 pm](https://cloud.githubusercontent.com/assets/4547737/6386064/1759227e-bdc3-11e4-9191-f04752ea5003.png)
![screen shot 2015-02-26 at 2 21 07 pm](https://cloud.githubusercontent.com/assets/4547737/6386062/17576df8-bdc3-11e4-9afc-54e24fee1393.png)
![screen shot 2015-02-26 at 2 21 11 pm](https://cloud.githubusercontent.com/assets/4547737/6386065/17599eac-bdc3-11e4-9001-e162ffb726a0.png)
![screen shot 2015-02-26 at 2 21 13 pm](https://cloud.githubusercontent.com/assets/4547737/6386063/1757cae6-bdc3-11e4-870c-67ddd468dd38.png)
![screen shot 2015-02-26 at 2 21 24 pm](https://cloud.githubusercontent.com/assets/4547737/6386069/17a29620-bdc3-11e4-8e65-bce2a49fbc75.png)
![screen shot 2015-02-26 at 2 21 27 pm](https://cloud.githubusercontent.com/assets/4547737/6386067/17a15db4-bdc3-11e4-94ed-69ae89efe585.png)
![screen shot 2015-02-26 at 2 21 32 pm](https://cloud.githubusercontent.com/assets/4547737/6386068/17a26506-bdc3-11e4-98b9-39ba858b8a09.png)
![screen shot 2015-02-26 at 2 21 35 pm](https://cloud.githubusercontent.com/assets/4547737/6386066/17a168d6-bdc3-11e4-8494-748feae820bd.png)

About -
![screen shot 2015-02-26 at 2 21 39 pm](https://cloud.githubusercontent.com/assets/4547737/6386070/17d7fb4e-bdc3-11e4-8096-092beaa248ff.png)
![screen shot 2015-02-26 at 2 21 45 pm](https://cloud.githubusercontent.com/assets/4547737/6386071/17d8bc78-bdc3-11e4-9626-4a2c13ff875f.png)
![screen shot 2015-02-26 at 2 21 51 pm](https://cloud.githubusercontent.com/assets/4547737/6386073/17d98310-bdc3-11e4-8fbf-55b7536c6297.png)
![screen shot 2015-02-26 at 2 21 53 pm](https://cloud.githubusercontent.com/assets/4547737/6386072/17d93b1c-bdc3-11e4-84c1-a14a6db6445e.png)

Network resources -
Large screens:
![screen shot 2015-02-26 at 2 32 23 pm](https://cloud.githubusercontent.com/assets/4547737/6386154/859b0a58-bdc4-11e4-8874-1c2895a89ee5.png)

Medium screens:
![screen shot 2015-02-26 at 2 32 13 pm](https://cloud.githubusercontent.com/assets/4547737/6386153/859a86dc-bdc4-11e4-815a-2f9b4e3735be.png)

Small screens:
![screen shot 2015-02-26 at 2 33 17 pm](https://cloud.githubusercontent.com/assets/4547737/6386155/85d63998-bdc4-11e4-9e59-e9a7f975506a.png)

**Comment by roman87** [comment]
So why do we left-justify the mobile view?
Also the actual problem in this issue is not solved. Here is what happens on a hires screen at full screen:
![selection_132](https://cloud.githubusercontent.com/assets/1326120/6400954/9f4aecf6-bdca-11e4-968a-6d01d8b0c8ba.png)

**Comment by luchia** [comment]
It looks odd in the screens because I'm using the Firefox Responsive Web Design Tool. I added a media query for all screens wider than 2000px and changed the width of the landing page.

![screen shot 2015-02-27 at 3 11 38 pm](https://cloud.githubusercontent.com/assets/4547737/6407596/6e0e1c5c-be93-11e4-9913-ad42c1d7742b.png)
![screen shot 2015-02-27 at 3 11 43 pm](https://cloud.githubusercontent.com/assets/4547737/6407597/6e17150a-be93-11e4-9394-4384c542d397.png)
![screen shot 2015-02-27 at 3 11 48 pm](https://cloud.githubusercontent.com/assets/4547737/6407598/6e5d92be-be93-11e4-9f86-5615d9e950cb.png)
![screen shot 2015-02-27 at 3 11 52 pm](https://cloud.githubusercontent.com/assets/4547737/6407599/6e5e1658-be93-11e4-9071-30bf245318bd.png)

**Comment by roman87** [comment]
Still an issue:
![selection_134](https://cloud.githubusercontent.com/assets/1326120/6427440/e6c1ccb4-bf4e-11e4-9d3e-2cd50603c723.png)

**Comment by luchia** [comment]
Can you please check again? I removed the background attachment and it's working on a screen res of 3000px on my machine now.

![screen shot 2015-03-02 at 1 34 53 pm](https://cloud.githubusercontent.com/assets/4547737/6434858/0525098a-c0e1-11e4-8f82-cbdf97c63f8f.png)
![screen shot 2015-03-02 at 1 35 00 pm](https://cloud.githubusercontent.com/assets/4547737/6434857/052382e0-c0e1-11e4-8463-d88f4a2d8007.png)

**Comment by DinisCruz** [comment]
cool, and looks good on the current version

Btw, can we also apply the same width to the: help, signup and login pages? that way the top nav doesn't move

**Comment by luchia** [comment]
I didn't want it to change because the landing page is separate from the application and those pages should be consistent with the app.

**Comment by DinisCruz** [comment]
kinda, at the moment there is already a significant difference between the anonymous top nav and the logged in user top nav

**Comment by luchia** [comment]
In what respect? The only difference should be the that there is one extra list item.

**Comment by roman87** [comment]
This is fixed. 
Here is the issue I think Dinis is talking about. 
This is how the landing page looks:
![Uploading Selection_137.png . . .]()

This is how the login page looks:
![Uploading Selection_138.png . . .]()

Which creates quite a disrupting visual experience for the user. 

This is how the Index page looks.
![selection_139](https://cloud.githubusercontent.com/assets/1326120/6465513/a3722326-c18f-11e4-8422-d4e6ba712fd8.png)

And full page view.

![selection_140](https://cloud.githubusercontent.com/assets/1326120/6465514/a3728596-c18f-11e4-8716-5205515450b2.png)

At the same time, we should not limit the user's browser real estate if they have a bigger screen, when they are using the application. So at some point this disruption from a limited real estate to a full browser window is necessary. The question is do we take the transition at login or do we take the transition after the landing page. I think we should do it at login.

**Comment by roman87** [comment]
Also marking for follow up with Brandon when the next beta is out.

**Comment by DinisCruz** [comment]
yap, I think it is ok to have a limit on the 'non logged in pages' , but after login the user should have the full width available

**Comment by roman87** [comment]
@luchia Where is this fixed?

**Comment by luchia** [comment]
For the screen width limitation? I thought you wanted to do it at login so I left it. Did you want me to put a limit on all non-logged in pages? What then happens with the help page, which can be viewed from a  logged-out perspective and a logged-in perspective?

**Comment by roman87** [comment]
As discussed on the call today, lets put the limit on all logged in pages except for the doc pages.

**Comment by luchia** [comment]
Alright, these are on the Lucy branch ready to be merged to Dev.

![screen shot 2015-03-10 at 5 27 47 pm](https://cloud.githubusercontent.com/assets/4547737/6570792/23ce2698-c74c-11e4-9e82-db7785f9d521.png)
![screen shot 2015-03-10 at 5 27 51 pm](https://cloud.githubusercontent.com/assets/4547737/6570793/240239f6-c74c-11e4-9469-7e6b5521afaa.png)
![screen shot 2015-03-10 at 5 27 53 pm](https://cloud.githubusercontent.com/assets/4547737/6570794/2432990c-c74c-11e4-8372-fc15ff6ec80f.png)

**Comment by roman87** [comment]
Ok now we have an issue with the logo ... :(..
![selection_146](https://cloud.githubusercontent.com/assets/1326120/6578486/c6fcbe74-c71a-11e4-9927-a912019333f0.png)

**Comment by roman87** [comment]
@luchia lets fix it ASAP, and then @DinisCruz could you merge Lucy->Dev-> master. This would be our customer beta.

**Comment by luchia** [comment]
Yup, fixed. There were a couple of other minor issues I found and fixed as well. I also ran it through all the browsers I have on my machine and it's looking good.

![screen shot 2015-03-11 at 7 11 47 am](https://cloud.githubusercontent.com/assets/4547737/6585495/016fa8a2-c7be-11e4-9213-f0d8f8f6e344.png)
![screen shot 2015-03-11 at 7 11 55 am](https://cloud.githubusercontent.com/assets/4547737/6585494/016f3b6a-c7be-11e4-99a1-6525d1e3a894.png)
![screen shot 2015-03-11 at 7 12 03 am](https://cloud.githubusercontent.com/assets/4547737/6585493/016e1c26-c7be-11e4-88c1-caa7b70f153a.png)

**Comment by michaelhidalgo** [comment]
@luchia, is this in your branch? I can help to test in saucelabs on different browsers/platforms.

**Comment by luchia** [comment]
Yes, it is.

**Comment by luchia** [comment]
I've assigned to Dinis to merge as I don't want to make any mistakes so close to launch.

**Comment by roman87** [comment]
Yey, finally fixed. @DinisCruz can you merge Lucy's branch into Dev and into master?

**Comment by DinisCruz** [comment]
sure ...

All code from **origin/Lucy** is now merged into Dev

![image](https://cloud.githubusercontent.com/assets/656739/6603137/0c903a3a-c818-11e4-8ed5-729da7f7272b.png)

with all tests passing

![image](https://cloud.githubusercontent.com/assets/656739/6603191/5e0e1242-c818-11e4-8f42-5544b8d6abf9.png)

**Comment by roman87** [comment]
Yep Looks good on Dev, can we merge Dev to master?

**Comment by DinisCruz** [comment]
yap its on master

![image](https://cloud.githubusercontent.com/assets/656739/6626559/7ff5be46-c8ef-11e4-8a0f-09412d9b96d8.png)

**Comment by roman87** [comment]
Cool. closing.

**Comment by roman87** [comment]
Actually I need to follow up with Brandon on this.

**Comment by roman87** [comment]
No responce from Brandon. TTL expired closing.
