### ISSUE TITLE
Changing query number in URL clears UI

### ISSUE THREAD

**Issue by pjenney58** [TeamMentor/TM_4_0_Design#627]
I know its a cheap shot, but making a single change in the query number in the URL results in a blank screen, thus:

![screen shot 2015-03-24 at 3 51 56 pm](https://cloud.githubusercontent.com/assets/2352439/6811418/079c7324-d23e-11e4-847f-7fdf32141567.png)

Steps to reproduce:

![screen shot 2015-03-24 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/2352439/6811481/a3bb8c40-d23e-11e4-905b-c89bba1b3991.png)

Change anything in the URL query-nnnnnnnn, press enter and boom. 

When its not a query, but an article reference it responds appropriately saying that the article doesn't exist.

**Comment by DinisCruz** [comment]
That is a good point we should fix that, @michaelhidalgo do you want to have a go, basically we need to detect when there are no results and show a page saying 'query not found' (or something similar)

**Comment by roman87** [comment]
Yes this is a good one. Basically it happens anytime you do something like this http://localhost:1337/show/blah

Gonna make it a P0, since  its nasty not to detect errors.

**Comment by michaelhidalgo** [comment]
In this case we should display the surrogate error page right?

**Comment by roman87** [comment]
Yes we should display a generic error page.

**Comment by michaelhidalgo** [comment]
This is the test that reproduces the problem : 

```coffeescript
  it.only  'Issue 606 - Changing query number in URL clears UI', (done) ->
    jade.login_As_User ()->
      page.open '/show/query-6204f2d47eb74*(*(*(*(', (html,$)->
        $('#containers .nav').assert_Is_Null();
        $('#list-view-article').assert_Is_Null();
      done()
```

**Comment by michaelhidalgo** [comment]
After the fix 

```coffeescript
it.only  'Issue 606 - Changing query number in URL clears UI', (done) ->
    jade.login_As_User ()->
      page.open '/show/query-6204f2d47eb74*(*(*(*(', (html,$)->
        $('#404-message').html().assert_Is_Not_Null();
        $('#404-message h1').html().assert_Is("An error occurred")
        $('#404-message p').html().assert_Contains("It&apos;s a HTTP 404 error - check the URL and refresh the browser.")
        done()
```

**Comment by michaelhidalgo** [comment]
With Pull Request https://github.com/TeamMentor/TM_4_0_Design/pull/647

**Comment by roman87** [comment]
this is fixed, will follow up with Pete when this is live

**Comment by michaelhidalgo** [comment]
This issue is partially fixed!. Note that when the HTTP 404 error is displayed, the Login and SignUp navigation links are displayed. Even when the user is already logged in.

This error is happening because when rendering the error page, we are not persisting the login status.

![screen shot 2015-04-07 at 10 28 38 pm](https://cloud.githubusercontent.com/assets/1732035/7038873/3b3796ea-dd75-11e4-916a-a8aba22cb274.png)

As a reference, I wrote the test for this scenario : 

```jade
it.only  'Issue 606 - Changing query number in URL clears UI', (done) ->
    jade.login_As_User ()->
      page.open '/show/query-6204f2d47eb74*(*(*(*(', (html,$)->
        $('#404-message').html().assert_Is_Not_Null();
        $('#404-message h1').html().assert_Is("An error occurred")
        $('#404-message p').html().assert_Contains("It&apos;s a HTTP 404 error - check the URL and refresh the browser.")
        
        #Login and Sign Up links still displayed
        $('#links').text().assert_Contains('Login');
        $('#links').text().assert_Contains('SignUp');
        $('#nav-sign-up').html().assert_Is('Sign Up')
        $('#nav-login').html().assert_Is('Login')
        done()
```

**Comment by michaelhidalgo** [comment]
This issue has been fixed here https://github.com/TeamMentor/TM_4_0_Design/pull/676

This is the unit test : 

```jade
it.only  'Issue 606 - Changing query number in URL clears UI', (done) ->
    jade.login_As_User ()->
      page.open '/show/query-6204f2d47eb7/query-f3d932e485feC', (html,$)->
        $('#404-message').html().assert_Is_Not_Null();
        $('#404-message h1').html().assert_Is("An error occurred")
        $('#404-message p').html().assert_Contains("It&apos;s a HTTP 404 error - check the URL and refresh the browser.")

        #Verifying navigation bar
        $('#links').text().assert_Not_Contains("Login");
        $('#links').text().assert_Not_Contains('SignUp');
        $('#nav-sign-up').assert_Is_Undefined()
        $('#nav-login').assert_Is_Undefined()
        $('#nav-user-logout span').html().assert_Is('Logout')
        $('#message').text().assert_Is('Found an issue? Send us an email.')
        done()
```
![screen shot 2015-04-07 at 10 54 45 pm](https://cloud.githubusercontent.com/assets/1732035/7039068/154a955a-dd79-11e4-919d-a72dd0ae8bc1.png)

**Comment by DinisCruz** [comment]
code merged

**Comment by michaelhidalgo** [comment]
Hi @roman87 , can you please give this issue a test :)

**Comment by roman87** [comment]
Ok, now this is really fixed and ready for follow up when the next beta comes out.

**Comment by DinisCruz** [comment]
added to https://github.com/TeamMentor/TM_4_0_Design/issues/675

**Comment by roman87** [comment]
@pjenney58 just wanting to close the loop on this. Can you take a look at latest beta and let me know if has been fixed to your satisfaction?

**Comment by pjenney58** [comment]
Yup.  Looks fine.

Cheers!

Pete

---)-------------------------------------
Security Innovation, Inc.
Peter H. Jenney

o:  978.694.1008 x164
m: 603.264.3961
Skype: PeteJenney

**Comment by roman87** [comment]
Great, closing.
