### ISSUE TITLE
Clicking next to the magnifying glass icon does not put cursor in the text box

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#687]
It seems like the area around the search icon is not responding to put cursor in the search field.
This comes to us from:
Description
================
Basically if you try to click next to the magnifying glass icon on the search page, the text cursor is not being put on the search field

Steps 
================
1. Go to the search page http://beta.teammentor.net/user/main.html
2. click next to the magnifying glass icon

Expected Results
================
1. Cursor should be located on the search field,

Take a look on the attached screenshot

![screen shot 2015-04-08 at 7 38 46 am](https://cloud.githubusercontent.com/assets/1326120/7093066/2f0392d2-df84-11e4-8421-3297a1bd928f.png)

**Comment by luchia** [comment]
This has been fixed and added to my PR for release -

![screen shot 2015-04-14 at 12 50 52 pm](https://cloud.githubusercontent.com/assets/4547737/7129550/59493316-e2a5-11e4-8eaf-a1ccf29bbebf.png)
![screen shot 2015-04-14 at 12 50 54 pm](https://cloud.githubusercontent.com/assets/4547737/7129555/616a7208-e2a5-11e4-90ae-3663c19e66e1.png)

**Comment by roman87** [comment]
Hmm. looks like there is still an issue:
This is from the latest Dev Branch:
![selection_180](https://cloud.githubusercontent.com/assets/1326120/7224019/41d10430-e6fa-11e4-85ff-6e46a3f1af3c.png)

**Comment by luchia** [comment]
Yup, my fix ends up failing because I used max-width to build the element originally. I spent time on this this morning and changed everything over to widths and it now works better and more reliably.

![screen shot 2015-04-21 at 9 25 43 am](https://cloud.githubusercontent.com/assets/4547737/7242744/b7349660-e808-11e4-8fbe-265c42ee0cc0.png)
![screen shot 2015-04-21 at 9 25 49 am](https://cloud.githubusercontent.com/assets/4547737/7242743/b7323ed8-e808-11e4-877f-9a95bb4cf984.png)
![screen shot 2015-04-21 at 9 25 58 am](https://cloud.githubusercontent.com/assets/4547737/7242745/b7af8e56-e808-11e4-81bd-8666088a5589.png)

I have created a PR for @DinisCruz that includes this and #710.

**Comment by DinisCruz** [comment]
merged

**Comment by DinisCruz** [comment]
added to https://github.com/TeamMentor/TM_4_0_Design/issues/687

**Comment by roman87** [comment]
I think it looks good. closing.
