### ISSUE TITLE
Font issue on the menu after logging in

### ISSUE THREAD

**Issue by roman87** [TeamMentor/TM_4_0_Design#758]
Seems like there is still a font issue with the menu in FF when user is logged in.
Here it is on beta:
![selection_217](https://cloud.githubusercontent.com/assets/1326120/7521430/cb79c112-f4bb-11e4-897d-0799aa59de4a.png)

And here it is on latest Dev:
![selection_218](https://cloud.githubusercontent.com/assets/1326120/7521436/d1c9fb04-f4bb-11e4-8e63-704ced695391.png)

**Comment by luchia** [comment]
This has been fixed on the Lucy branch -

![screen shot 2015-05-08 at 8 36 37 am](https://cloud.githubusercontent.com/assets/4547737/7527331/777a6826-f55d-11e4-9493-55b6eeb46a93.png)

I will create a PR at the end of my day today with all my changes.

**Comment by DinisCruz** [comment]
added to CR9 https://github.com/TeamMentor/TM_4_0_Design/issues/739

**Comment by roman87** [comment]
Still an issue here:
This is before the login:
![selection_224](https://cloud.githubusercontent.com/assets/1326120/7558427/1bb26e3c-f772-11e4-8c6b-0ef484ec4e77.png)
And this is after:
![selection_223](https://cloud.githubusercontent.com/assets/1326120/7558436/3773fb04-f772-11e4-87e1-92ebd75698fa.png)

**Comment by luchia** [comment]
I think I got it this time. A weird bug between two different classes -

![screen shot 2015-05-12 at 9 10 51 am](https://cloud.githubusercontent.com/assets/4547737/7576984/d9b5088a-f886-11e4-9318-d66f6cd749b0.png)
![screen shot 2015-05-12 at 9 10 54 am](https://cloud.githubusercontent.com/assets/4547737/7576985/d9b70018-f886-11e4-8e19-77cefd157c21.png)
![screen shot 2015-05-12 at 9 11 32 am](https://cloud.githubusercontent.com/assets/4547737/7576998/ef9f4408-f886-11e4-91ca-d13db76a4f83.png)
![screen shot 2015-05-12 at 9 11 44 am](https://cloud.githubusercontent.com/assets/4547737/7576999/efa0cb84-f886-11e4-8dfe-5db21af1f4ba.png)

**Comment by roman87** [comment]
This looks good. However, if you look even at your screenshots, you see that the logged in menu is higher than non logged in. i.e. the letters are closer to the top of the browser. Is that on purpose?

**Comment by luchia** [comment]
It has to be, otherwise we can't fit in the contact message without stretching the navigation down and mucking up the margins for the rest of the application.

**Comment by roman87** [comment]
Looks good then. Closing.
