### ISSUE TITLE
Markdown articles do not show correctly in snippet

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#903]

**Comment by DinisCruz** [comment]
where is this happening?

**Comment by romichg** [comment]
Once you fix #902 it will become apparent :)

**Comment by romichg** [comment]
Happens on the Dev branch of tm-sme/Lib_UNO

**Comment by romichg** [comment]
This also happens when you search for "Welcome To" with the 2nd article down.

**Comment by michaelhidalgo** [comment]
![screen shot 2015-08-10 at 15 28 33](https://cloud.githubusercontent.com/assets/1732035/9184721/3c5334ce-3f74-11e5-9ff3-5afe746b5570.png)

**Comment by romichg** [comment]
Current solution looks for first 200 characters. We cannot be breaking a word in the middle. We have to look for first 200 characters +  .*\s

**Comment by michaelhidalgo** [comment]
This has been fixed, we need to generate the Lib_UNO-json again.

**Comment by romichg** [comment]
This is still an issue. The last words are broken because we truncate at 200 characters. So the word breaks in the middle. We need to ether look for the end of the beginning of the word before we truncate.

**Comment by michaelhidalgo** [comment]
Hey, do you have an article with this behaviour? I fixed the script, so in order to correct those cases, we need to generated the Lib_UNO-json again.

I did it offline and did not found any issue (i.e they were fixed),however, I must have missed one.

**Comment by romichg** [comment]
hmm... the current tmdev01-beta has new content re-generated yesterday, and all articles are still this way.

**Comment by romichg** [comment]
just pick any article: 
![selection_039](https://cloud.githubusercontent.com/assets/1326120/9774032/fd7bcdb2-5713-11e5-943d-9addeb51e433.png)
