### ISSUE TITLE
Link color stays on after clicking

### ISSUE THREAD

**Issue by romichg** [TeamMentor/TM_4_0_Design#976]
To replicate. Go to the bottom, click "next"  As you can see the "next" is still green
![selection_031](https://cloud.githubusercontent.com/assets/1326120/9775242/cb27c318-571b-11e5-953c-5120c5289899.png)

**Comment by luchia** [comment]
This has been fixed, I'll submit a PR shortly.

**Comment by romichg** [comment]
Still an issue for the "Back Top" link, and all the nav links except for the home one

![selection_044](https://cloud.githubusercontent.com/assets/1326120/9805948/ffa73c94-580c-11e5-8375-7ff8a53a1eaa.png)
![selection_043](https://cloud.githubusercontent.com/assets/1326120/9805950/019f9e06-580d-11e5-9e25-cb41fb7b22f3.png)

**Comment by luchia** [comment]
Ohh, I thought you only wanted it on the pagination. I like it in the navigation, it shows the user where they are in the application.

**Comment by romichg** [comment]
Ok, but it needs to work consistently. At the moment it doesn't stick on the home button, but stick everywhere else. It also doesn't solve the back top button issue above

**Comment by luchia** [comment]
Yup, I caught both of those yesterday as I thought you meant just the pagination initially. It sticks to the home button on mine, do you have the latest TM_Static?

![screen shot 2015-09-12 at 10 29 24 am](https://cloud.githubusercontent.com/assets/4547737/9829178/371a9b26-5939-11e5-91e0-cf9faaa924ae.png)

**Comment by romichg** [comment]
Ok looks good. The only problem is that after initial logon the home button is not green, which is kinda inconsistent. Not a biggie.

**Comment by romichg** [comment]
Also, after clicking home, if you click anywhere on the page the color goes away. I am not sure if this is more work than it is worth to keep the colors on.

**Comment by luchia** [comment]
Okay, I removed it :)

**Comment by romichg** [comment]
lol you gave up easily. 
This is done.
